FROM rust:1.78 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/dbounty-backend /usr/local/bin/dbounty-backend
EXPOSE 8080
CMD ["dbounty-backend"]
